name: Create GitHub deployment
description: Creates a GitHub deployment
author: Bruce Weirdan
branding:
  icon: upload-cloud
  color: orange
inputs:
  token:
    required: true
    description: GitHub repository-scoped token
  ref:
    required: false
    description: The ref to deploy. This can be a branch, tag, or SHA. Default is the branch that the workflow is triggered on.
  task:
    required: false
    default: deploy
    description: Specifies a task to execute, e.g. `deploy` or `deploy:migrations`
  auto_merge:
    required: false
    default: "true"
    description: Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch
  payload:
    required: false
    default: ""
    description: JSON payload with extra information about the deployment
  environment:
    required: false
    default: production
    description: Name for the target deployment environment (e.g., `production`, `staging`, ``qa`)
  description:
    required: false
    default: ""
    description: Short description of the deployment
  transient_environment:
    required: false
    default: "false"
    description: Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future
  production_environment:
    required: false
    default: "false" 
    description: "Specifies if the given environment is one that end-users directly interact with. Default: `true` when environment is production and `false` otherwise."
  required_contexts:
    required: false
    default: "[]"
    description: The status contexts to verify against commit status checks. If you omit this parameter, GitHub verifies all unique contexts before creating a deployment. To bypass checking entirely, pass an empty array. Defaults to all unique contexts.
outputs:
  deployment_id:
    description: Identifier of the created deployment
runs:
  using: 'node12'
  main: 'dist/index.js'
